<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bibliographic documents</name>
   <tag></tag>
   <elementGuidId>1b7e8a8d-d29a-419a-a664-eaedba27834c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fe1016e-c452-43dd-a8d8-547f9a570d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>2597a500-42d3-4790-af41-d8bb432e6cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:op()</value>
      <webElementGuid>ac43b667-5a73-47f1-a6d1-326014853c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>946ca7ac-fc8f-468c-8133-e1a2502d6666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink2</value>
      <webElementGuid>e4957e1a-a6f8-4b57-87c3-a18894cd2c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clickOnFolder(&quot;2&quot;)</value>
      <webElementGuid>50fdd2e8-f6b0-4519-b05f-93c4640d5b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bibliographic documents</value>
      <webElementGuid>e72183ad-7d8f-4c28-8ae2-c9b3498f6b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink2&quot;)</value>
      <webElementGuid>d1026833-dd65-475f-a153-54bcf26feaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink2']</value>
      <webElementGuid>451b982e-7e3b-48b1-a307-f21ba474a439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder2']/table/tbody/tr/td[4]/a</value>
      <webElementGuid>bcfcbf9d-d4b7-4e1a-bd72-b67d1b37ea64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bibliographic documents')]</value>
      <webElementGuid>19cbf24d-b621-45d6-a008-31527505f0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BIBLIOGRAPHY'])[1]/following::a[2]</value>
      <webElementGuid>f091a2bc-57ca-4fda-a2c7-eb82ed1c770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Options'])[1]/following::a[5]</value>
      <webElementGuid>04bbb24a-1c1a-4c8b-ba5c-003e33647e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Reports'])[1]/preceding::a[2]</value>
      <webElementGuid>6c1ba74c-f5d3-4959-996a-c3fdb9c17605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authority lists'])[1]/preceding::a[4]</value>
      <webElementGuid>fe00368a-daf7-4939-8320-8d679f82f832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bibliographic documents']/parent::*</value>
      <webElementGuid>54e5f11e-e08b-4347-adba-dfa7becf834f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:op()')])[2]</value>
      <webElementGuid>6d6abdd3-f056-43ea-a932-e70961a7d66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>62703a6b-5994-4b93-af41-c028ce250932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:op()' and @id = 'itemTextLink2' and (text() = 'Bibliographic documents' or . = 'Bibliographic documents')]</value>
      <webElementGuid>3d71d5f7-66f9-4662-bb15-f9c7be987c9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
