<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BIBLIOGRAPHY</name>
   <tag></tag>
   <elementGuidId>972a475c-cce5-4e6a-804d-4bd76bb54bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c133c66b-5709-4212-93d1-f652347f8cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>3bc556be-dad3-4ee1-badb-a26575ffe359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:op()</value>
      <webElementGuid>8fa9c38c-7080-427e-9056-0e96c53e651f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>817f1a56-5e11-4c56-8b8d-9aaf929f9b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink1</value>
      <webElementGuid>e95587b8-6a14-4796-865e-f6bc724d38ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clickOnFolder(&quot;1&quot;)</value>
      <webElementGuid>6e2ccbd6-6152-4126-860e-e3ccc259e75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BIBLIOGRAPHY</value>
      <webElementGuid>0da15f76-8238-41f6-bad3-10102f512d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink1&quot;)</value>
      <webElementGuid>b4288725-2f80-4a40-b427-7294d7d8d462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink1']</value>
      <webElementGuid>8dcae3d7-db3f-4e01-85c9-ce17963e236f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder1']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>e29e5a13-484d-4061-a28b-f760e5c0f8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BIBLIOGRAPHY')]</value>
      <webElementGuid>b8b85906-9e76-4439-8521-4bdbaa171c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Options'])[1]/following::a[3]</value>
      <webElementGuid>fc97d35c-4d8a-4949-9142-315b41e98929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logoff'])[1]/following::a[3]</value>
      <webElementGuid>7b00bb55-4666-45ea-9b21-241b146e3f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JURISPRUDENCE'])[1]/preceding::a[2]</value>
      <webElementGuid>749bded5-a55c-418e-89b3-500f521bb3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRACTICAL CONTENT'])[1]/preceding::a[4]</value>
      <webElementGuid>0969d357-9924-46ad-89e4-60ad4f226403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BIBLIOGRAPHY']/parent::*</value>
      <webElementGuid>24836b48-e456-4cda-9343-a38fa1cd0ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:op()')]</value>
      <webElementGuid>90f9810c-6cab-4ec1-8eab-c84b7c7fab53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[3]/a</value>
      <webElementGuid>8991a67f-80af-4e95-885b-838988289892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:op()' and @id = 'itemTextLink1' and (text() = 'BIBLIOGRAPHY' or . = 'BIBLIOGRAPHY')]</value>
      <webElementGuid>f3115d5d-9aa4-4757-8cce-2d898f72f12f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
