<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Site</name>
   <tag></tag>
   <elementGuidId>18eea0ab-8704-4fa3-a88d-ed7dc05da8a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pictos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='header-banner-links']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5bb7e8c6-3d43-421f-93c3-89edf3ddcb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://2022-11-11-4-12.qa-webbuildercs.com</value>
      <webElementGuid>be3a8d71-33b1-4ecd-807e-22eee621608a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_Blank</value>
      <webElementGuid>3906cce7-2b4d-48b3-b5ca-fdfa275dd5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pictos</value>
      <webElementGuid>34f418cd-af04-4081-94cc-6219b2477403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Site</value>
      <webElementGuid>d1ae360a-e95d-434f-a379-efabc8b64a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-banner-links&quot;)/li[1]/a[@class=&quot;pictos&quot;]</value>
      <webElementGuid>fc8ce854-7165-4648-9b3e-647a1bf5dd24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='header-banner-links']/li/a</value>
      <webElementGuid>c5eec8e9-5890-4ee5-9eea-443a1aa87b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Site')]</value>
      <webElementGuid>601834cf-350b-473c-aca6-14bb00b165be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Builder CS'])[1]/following::a[1]</value>
      <webElementGuid>c374aff0-97aa-475a-8560-cb927a8b4e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-------'])[1]/following::a[2]</value>
      <webElementGuid>ec716cc7-a513-4cbb-a0ee-c889c697bb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; How-To'])[1]/preceding::a[1]</value>
      <webElementGuid>f47ac175-3b82-45fb-9a3f-64d95e928ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEA INCUBATOR'])[1]/preceding::a[2]</value>
      <webElementGuid>f18331e4-00cd-4b40-bdcf-11d905ebafc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Site']/parent::*</value>
      <webElementGuid>301a7a7e-08db-4d49-b207-3bc0f8539f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://2022-11-11-4-12.qa-webbuildercs.com']</value>
      <webElementGuid>6c5ce400-38df-4762-92e0-397dd3597d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>d5d29870-a339-45bc-b4cc-10af33dcfd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://2022-11-11-4-12.qa-webbuildercs.com' and (text() = 'View Site' or . = 'View Site')]</value>
      <webElementGuid>c6d4683f-d3d1-4f74-a15e-fb84ec22d41c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
