<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Language_buttonInform</name>
   <tag></tag>
   <elementGuidId>47a90fda-7e10-45f8-b127-939cae018124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.buttonInform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Logon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>972a1666-d344-48c6-982a-f260bc4e7907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9295bf3d-c955-4973-8187-096b2e5b1234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonInform</value>
      <webElementGuid>cc1c7652-5980-4a18-92d8-14babcdf10c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Logon</value>
      <webElementGuid>fe041d38-917b-439b-848e-bc60a6a4312c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:normalizarUserID();</value>
      <webElementGuid>233b8839-0246-445a-a968-cead76154120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[3]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[@class=&quot;buttonInform&quot;]</value>
      <webElementGuid>3ae42dd5-fa33-4d5a-8ae5-e4ab716d60d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Logon']</value>
      <webElementGuid>c25ddaba-9c22-42d3-858d-ad1dbdaf7edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>7bca4f02-65e4-4759-9326-00fe78519fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>545b15bf-2307-4cb6-9786-6983706eabd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
