<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WIP</name>
   <tag></tag>
   <elementGuidId>c4ee0949-45b8-497f-b23c-626e454d7852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lnkHeaderWIP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkHeaderWIP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cce6b9de-9cad-4da3-96bd-d8a0cd9a9eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkHeaderWIP</value>
      <webElementGuid>08ec89c8-b274-4022-a97f-6500f8a1798f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>wip.do</value>
      <webElementGuid>7acfb52d-3342-4e40-a5f4-c65ef8a26ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WIP</value>
      <webElementGuid>88c51f1c-441e-4c79-addc-1570b6c83a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkHeaderWIP&quot;)</value>
      <webElementGuid>344dfc59-c6f8-49fc-ae03-2a8e55fabe60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnkHeaderWIP']</value>
      <webElementGuid>b39f790b-6a37-49e5-b598-154a59a008eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WIP')]</value>
      <webElementGuid>566ced4d-d339-465f-ab38-fc22cac36e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BR-CLIENT-c038kdtgcma05'])[1]/following::a[1]</value>
      <webElementGuid>ea842418-e69c-4d23-a69c-37ae4eb535cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thomson Reuters'])[1]/following::a[2]</value>
      <webElementGuid>5d91e925-a356-4a69-b706-fe167c15a02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product workbench'])[1]/preceding::a[1]</value>
      <webElementGuid>054d3e8b-cc91-4760-ae6c-6c450c373d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/preceding::a[2]</value>
      <webElementGuid>504f12c6-e54c-4e54-82d6-3a9d5c9c4683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WIP']/parent::*</value>
      <webElementGuid>a6a7002b-ae0a-406a-bfc1-e591b46dbf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'wip.do')]</value>
      <webElementGuid>19241dc6-1ab6-44e7-a337-cf37ec22b732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>6ff8ccd9-3318-4c47-876c-6d7988c9fee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkHeaderWIP' and @href = 'wip.do' and (text() = 'WIP' or . = 'WIP')]</value>
      <webElementGuid>9ed3d9f3-bdac-4530-aa01-d425acaf2737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
