<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ANALYSIS DATA_clicker_datos_analisis</name>
   <tag></tag>
   <elementGuidId>c60e1eba-7033-4998-a437-ed980f52f7e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clicker_datos_analisis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='clicker_datos_analisis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ad18488-859b-4dd2-928d-91a0dc92b75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clicker_datos_analisis</value>
      <webElementGuid>900d618a-fff6-4b03-b93b-108cbd8b989a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/plus.gif</value>
      <webElementGuid>37294f4a-da09-4102-915d-a156fbab7179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>f80593f0-cbaf-46d7-a391-1f22da350ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2ea51c16-07ee-46a7-b37e-1afea038d258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clicker_datos_analisis&quot;)</value>
      <webElementGuid>f6e6e5e4-11ff-45b2-ae8c-e2aac6baebc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='clicker_datos_analisis']</value>
      <webElementGuid>679d8958-717a-443a-871b-78acfa620a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContentDetailsLeft']/table[7]/tbody/tr/td/a/img</value>
      <webElementGuid>b4e6b209-4230-4659-a373-3b80fff6aeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[7]/tbody/tr/td/a/img</value>
      <webElementGuid>52f29b15-ad0d-477c-abb4-c111459b546e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'clicker_datos_analisis' and @src = 'images/plus.gif']</value>
      <webElementGuid>74d1e861-0d50-4300-a497-141bb2fb415e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
