<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FormatHTMLRTFPDFXML_2</name>
   <tag></tag>
   <elementGuidId>6ce03f3b-db2b-417e-a5b0-5a67a8839a1e</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Document Edition/input_FormatHTMLRTFPDFXML_2.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSubmitEdit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSubmitEdit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'btnSubmitEdit' and @name = '2']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Document Edition/input_FormatHTMLRTFPDFXML_2.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb56d84c-605a-422e-80f0-f93068ec9b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0898d9f-d597-4eea-9670-e222fb0a1f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSubmitEdit</value>
      <webElementGuid>d3362429-caac-46cf-93b9-decafc9ae13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doUpdateReference()</value>
      <webElementGuid>b3f2be79-1c99-478e-b318-f906d8426e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>380b07f8-9818-4be0-b994-9630f822cba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonInform</value>
      <webElementGuid>875333c1-e01e-4342-8dcf-789e674bf41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>2914539b-ac24-4d7a-865b-094c96d05244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSubmitEdit&quot;)</value>
      <webElementGuid>31ec5e4a-8925-4c25-bd21-d4bbf2d845a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSubmitEdit']</value>
      <webElementGuid>a7ac9eff-180e-4d72-bc90-06b23673a775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='referenceForm']/table/tbody/tr/td/input</value>
      <webElementGuid>d208209c-2f26-48af-9342-3ca5c2fc867b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/input</value>
      <webElementGuid>a3f2fbd8-1073-4adb-a55d-34be7b93a808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnSubmitEdit' and @name = '2']</value>
      <webElementGuid>9cacf16a-81e5-455d-9d06-22341be3e215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnCancelEdit']</value>
      <webElementGuid>cacea1a0-8550-4e5e-8d47-3a1c5b04b8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='referenceForm']/table/tbody/tr/td/input[2]</value>
      <webElementGuid>3c96f0d5-55d2-4eba-874a-fa78aaaa249d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/input[2]</value>
      <webElementGuid>f60c38c3-12c6-4322-b250-c046b09ff3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnCancelEdit' and @name = '2']</value>
      <webElementGuid>e5d4ecf2-7012-43ab-b813-635ec2628f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
