<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_WIP</name>
   <tag></tag>
   <elementGuidId>01e66d8f-49c7-468c-8cb8-422bf46642f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.bg_topnavselected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='BR-CLIENT-c038kdtgcma05'])[1]/following::td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a41eff38-d289-483e-a081-0123155c2098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>190</value>
      <webElementGuid>05ac765b-b68b-44c6-824b-e3905b207f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg_topnavselected</value>
      <webElementGuid>1e8d5aa5-94ce-4a26-ab9e-11634a6b3f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WIP</value>
      <webElementGuid>0aa2ab85-db2f-4b36-b74d-4ba85f3673f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[3]/tbody[1]/tr[2]/td[@class=&quot;bg_topnav&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;bg_topnavselected&quot;]</value>
      <webElementGuid>e605129e-aca3-46d1-b266-17ea4db264ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BR-CLIENT-c038kdtgcma05'])[1]/following::td[5]</value>
      <webElementGuid>3962e904-1134-47cb-ba30-16b8cd08ce49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thomson Reuters'])[1]/following::td[8]</value>
      <webElementGuid>0729fc04-b857-44d6-bbbd-6f971bdcf3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product workbench'])[1]/preceding::td[1]</value>
      <webElementGuid>e236d179-7d1b-4c72-a0c3-ec0785fc44ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>c05ea3b5-d75a-4e08-8b17-27d127a7b5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'WIP' or . = 'WIP')]</value>
      <webElementGuid>e40c6b63-a574-4f6f-8b4c-0a42281f0f72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
