<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FormatHTMLRTFPDFXML_2</name>
   <tag></tag>
   <elementGuidId>6a7cf2ed-010f-4ac8-8358-d504e0218666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnGoBack</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnGoBack']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45ee7913-0be2-45e3-be9c-bcb21b53f312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ba684cd-d3dc-434d-a763-d594b78e5ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGoBack</value>
      <webElementGuid>55b71265-c0d6-4b08-b4e1-59987b7f07c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:atrasFaseII('../GCMSWeb/biblio/doMenu.do?dispatch=resu')</value>
      <webElementGuid>5560644a-8038-44ad-8bfd-07e7b70d2ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9bb3316b-dbd7-49cb-ac8c-a699fbd3448f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonInform</value>
      <webElementGuid>dd61d845-ca93-483e-82f4-110fd1d6a17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go back</value>
      <webElementGuid>cc3a1858-6c6f-45fb-a7a4-b93f9ab42135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGoBack&quot;)</value>
      <webElementGuid>960ed13e-0b9e-4f33-890e-af6d649470bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnGoBack']</value>
      <webElementGuid>a6711eb9-db34-4061-a87b-d767eadc12eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td/input[4]</value>
      <webElementGuid>5eca242a-4660-40c7-be0a-7448b7409767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnGoBack' and @name = '2']</value>
      <webElementGuid>85b282c0-d5a2-4d93-a95b-30e3f95f4340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
