<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DTR199219</name>
   <tag></tag>
   <elementGuidId>d6089c09-83a2-4e3f-b7b6-6bd5a842bbb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.referencia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultsTable']/tbody/tr[3]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03462547-042e-4dc8-b41c-859a96f1dd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>referencia</value>
      <webElementGuid>c102f7a6-9f68-41ad-817a-9aa71487509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:viewReferenceDetail(63186298,'../..');</value>
      <webElementGuid>f88456d5-658f-4185-889d-661149c1f4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								DTR\1992\19
							</value>
      <webElementGuid>d64a0338-bf93-441d-ae43-3b529d11cf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsTable&quot;)/tbody[1]/tr[3]/td[@class=&quot;tdContent&quot;]/a[@class=&quot;referencia&quot;]</value>
      <webElementGuid>278eac63-d0d8-4ae7-9f21-ddea298cc0c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultsTable']/tbody/tr[3]/td[2]/a</value>
      <webElementGuid>278ff92f-d474-4eaa-bfce-4cf415527a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DTR\1992\19')]</value>
      <webElementGuid>2cdedff2-bb9a-4e0f-b69b-78b1bbf463ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::a[1]</value>
      <webElementGuid>82d78d92-d513-46f3-9f0a-01c637d7783a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bibliography type'])[1]/following::a[1]</value>
      <webElementGuid>d2ac7216-6301-46e7-9516-9a875e68737b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='artículo'])[1]/preceding::a[1]</value>
      <webElementGuid>2a805253-5eab-481b-8052-0bb92e0ac3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DTR\1992\19']/parent::*</value>
      <webElementGuid>520ce114-12ae-482b-8201-5f31faede4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:viewReferenceDetail(63186298,'../..');&quot;)]</value>
      <webElementGuid>faffb89a-c932-435e-af45-40b22fb008b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/a</value>
      <webElementGuid>a972acef-2f18-41fa-90a8-24ba1110e7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:viewReferenceDetail(63186298,&quot; , &quot;'&quot; , &quot;../..&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = '
								DTR\1992\19
							' or . = '
								DTR\1992\19
							')]</value>
      <webElementGuid>1a45524f-11bb-428c-820f-aac7284e8e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
