<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Site</name>
   <tag></tag>
   <elementGuidId>8b132a26-b816-4d48-aa2c-71c7a0981a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='header-banner-links']/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pictos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1a58686-13c0-42a8-b034-6a1dee9e7635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://2022-11-11-4-12.qa-webbuildercs.com</value>
      <webElementGuid>965bf272-a90c-4301-96c2-646b2e23af44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_Blank</value>
      <webElementGuid>dddd3cce-c60e-4ae9-868c-bd5225dd61af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pictos</value>
      <webElementGuid>136cd83b-edca-456b-878e-ee4bdcfc2ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Site</value>
      <webElementGuid>81598d0b-c071-4673-ae21-5372dacb5845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-banner-links&quot;)/li[1]/a[@class=&quot;pictos&quot;]</value>
      <webElementGuid>b7c67a7b-37ad-41c0-bce1-1bb5a5846995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='header-banner-links']/li/a</value>
      <webElementGuid>620de337-7ccf-4f85-8231-e4f0f5fb7f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Site')]</value>
      <webElementGuid>b6c8da68-f654-4dbc-85bd-4d9959d36145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Builder CS'])[1]/following::a[1]</value>
      <webElementGuid>b3033286-47b7-47c0-befc-14bdea71cf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-------'])[1]/following::a[2]</value>
      <webElementGuid>f5b2bb97-dc86-4481-b8cb-360ca3e7bbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; How-To'])[1]/preceding::a[1]</value>
      <webElementGuid>1aec8409-dba9-496b-a8ae-f5cb73e102ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEA INCUBATOR'])[1]/preceding::a[2]</value>
      <webElementGuid>ec943274-779d-459b-a92c-d137ec4d6c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Site']/parent::*</value>
      <webElementGuid>6dd671f2-2019-469c-aafd-3d2fc8895a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://2022-11-11-4-12.qa-webbuildercs.com']</value>
      <webElementGuid>49b24b76-d370-46dc-9ea0-7e3d239d6200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>8c9c9b90-1d81-4bc9-b7d4-9232a3630fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://2022-11-11-4-12.qa-webbuildercs.com' and (text() = 'View Site' or . = 'View Site')]</value>
      <webElementGuid>f42c8ef1-01d8-47b7-b623-8c8242d984bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
