<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FormatHTMLRTFPDFXML_2</name>
   <tag></tag>
   <elementGuidId>99aab8f4-ef56-4090-a241-ed2bc2cff95d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnEditarReferencia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnEditarReferencia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34928145-4428-485f-856a-af01db2bb667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d5a7ed7-6f85-465a-937d-4fa46a47a20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEditarReferencia</value>
      <webElementGuid>33d7be19-514d-4375-8dcc-09d10f21f63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>editReference(63186298)</value>
      <webElementGuid>193f5653-2295-4fcf-a4c6-286958d43f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3b7fdb66-a8c2-4c8c-b614-378ac679bd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonInform</value>
      <webElementGuid>96363bcc-cca4-4bce-843e-14a34e0382fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>1b218749-2a66-476a-8065-44eecbfe108a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEditarReferencia&quot;)</value>
      <webElementGuid>b4f56193-c8d9-4999-b96e-7d6aa1caf76e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnEditarReferencia']</value>
      <webElementGuid>233c24c5-d5be-4827-ad9e-3d6a2b16b44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/input[2]</value>
      <webElementGuid>7eff2f3e-23ae-43f8-9ba5-9a24e2a68f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnEditarReferencia' and @name = '2']</value>
      <webElementGuid>7b1fb924-4d24-40c6-b1ad-c158d08d6f36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
