<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BIBLIOGRAPHY</name>
   <tag></tag>
   <elementGuidId>72a7b7c9-9eba-47a6-84b8-d47ff016001c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3076ded-2915-4bbf-b5b3-bbe1410114a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>008802b7-1462-45f2-b7ad-9a47b6e27913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:op()</value>
      <webElementGuid>43896306-f389-48bb-a91c-40b8b39043e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>ef88a6ae-3f5d-4df1-bc4e-8c3ae9062823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink1</value>
      <webElementGuid>25b578b1-02f0-432b-a913-a08348a90756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clickOnFolder(&quot;1&quot;)</value>
      <webElementGuid>716d9561-b650-409e-9c03-961d60d84065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BIBLIOGRAPHY</value>
      <webElementGuid>54616d05-be69-43d5-be8d-dea53768a7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink1&quot;)</value>
      <webElementGuid>c82cfcd1-5bc5-42f9-91cd-ecc3a6260bc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink1']</value>
      <webElementGuid>6dd05d75-d1a1-4649-bce5-6802d815b6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder1']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>1bfefa1f-1efc-4667-adac-211b4adefcda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BIBLIOGRAPHY')]</value>
      <webElementGuid>a3ab2c85-5249-45c6-8b47-ab83f57e2f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Options'])[1]/following::a[3]</value>
      <webElementGuid>bb1d46c9-6ed5-4ba5-9e88-78bd41ee4d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logoff'])[1]/following::a[3]</value>
      <webElementGuid>bb9ab764-e1b0-4098-8fbe-8a0fa0821c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bibliographic documents'])[1]/preceding::a[2]</value>
      <webElementGuid>61abe04a-a488-4be5-8aae-7a3f16918b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[4]</value>
      <webElementGuid>c4464da0-531d-4bdd-8aea-02c76faaefe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BIBLIOGRAPHY']/parent::*</value>
      <webElementGuid>f37ecdab-4d54-419e-ab68-3aefa98f5df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:op()')]</value>
      <webElementGuid>312a3b80-f77d-4aaa-8fb7-a3354d996b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[3]/a</value>
      <webElementGuid>d61521f8-7f94-4215-8ee4-7f5cfde982e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:op()' and @id = 'itemTextLink1' and (text() = 'BIBLIOGRAPHY' or . = 'BIBLIOGRAPHY')]</value>
      <webElementGuid>1ae1a98e-b7e6-4355-95ca-c5761df7f71c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
