<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logoff</name>
   <tag></tag>
   <elementGuidId>5a4b43c0-58f1-430c-81aa-3ef9bee41cda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lnkHeaderLogOut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkHeaderLogOut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17077248-63ee-41e1-8acf-5c64d1e0b36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkHeaderLogOut</value>
      <webElementGuid>6b47bf04-00ba-47af-8753-94df1267bb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>actionLogon.do?operacion=0</value>
      <webElementGuid>2c090cf7-3780-4a45-b00d-593778875e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logoff</value>
      <webElementGuid>73083590-5eb5-430d-ac24-b967bb985545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkHeaderLogOut&quot;)</value>
      <webElementGuid>b448c0e0-5b98-48c8-b2a8-40c16cf695e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnkHeaderLogOut']</value>
      <webElementGuid>2969b352-564e-418c-88f5-c088132240b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logoff')]</value>
      <webElementGuid>ba79c637-ccc1-49b3-8eb8-cd8c6ef80b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/following::a[1]</value>
      <webElementGuid>5fe5de9f-2217-41d3-baab-45c945fdaf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product workbench'])[1]/following::a[2]</value>
      <webElementGuid>1b407e63-fa90-4125-b4db-87f77a62d525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Options'])[1]/preceding::a[1]</value>
      <webElementGuid>11adb27e-b35d-471e-a943-39f6add36a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BIBLIOGRAPHY'])[1]/preceding::a[3]</value>
      <webElementGuid>6176030a-5523-48c5-a520-eeb99d28ccdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logoff']/parent::*</value>
      <webElementGuid>44765f3e-4b3c-4263-98e6-7e74932c93cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'actionLogon.do?operacion=0')]</value>
      <webElementGuid>24737ac4-581d-40d6-8714-be21ed4ed500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[5]/a</value>
      <webElementGuid>3e7b128b-f047-47de-91bc-b5dac6159d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkHeaderLogOut' and @href = 'actionLogon.do?operacion=0' and (text() = 'Logoff' or . = 'Logoff')]</value>
      <webElementGuid>1c1c3aa6-0e70-482c-b712-ac4bb68ddfc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
