<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BIBLIOGRAPHY</name>
   <tag></tag>
   <elementGuidId>2eb3c8e0-b1b8-4af2-bf82-091c56d861e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47f78c73-adc4-4d11-891d-28e7bdab8fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>6cea82bb-cd72-40fe-9547-8ffbcd134230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:op()</value>
      <webElementGuid>8072486c-550c-4e8e-8be5-c6e2bdb7d24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>a315d418-6897-4bad-96be-0d435c85bc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink1</value>
      <webElementGuid>2566bbcc-1a0a-4630-b913-d48326c5e3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clickOnFolder(&quot;1&quot;)</value>
      <webElementGuid>73d6d975-259e-43d7-9af2-7ef82654a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BIBLIOGRAPHY</value>
      <webElementGuid>10e3c186-041c-431e-a0b5-b9e44432b1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink1&quot;)</value>
      <webElementGuid>0539cde1-94c9-4243-96ad-169c73619b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink1']</value>
      <webElementGuid>d8c42ea8-c280-42bc-bef4-e30fa960c189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder1']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>cecc1cb8-a63c-45fd-8a4d-020621edd65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BIBLIOGRAPHY')]</value>
      <webElementGuid>6d4ee9b5-8640-4f56-956f-70d75040b421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Options'])[1]/following::a[3]</value>
      <webElementGuid>e78d9cc5-8ebc-4753-a67a-7a3f30a4c6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logoff'])[1]/following::a[3]</value>
      <webElementGuid>11bec555-d23a-438b-9220-1202b1efc2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bibliographic documents'])[1]/preceding::a[2]</value>
      <webElementGuid>6cfc4456-cd29-485b-836c-9a1ba241b3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[4]</value>
      <webElementGuid>d98c94d2-20c5-42ba-b860-1283339c79ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BIBLIOGRAPHY']/parent::*</value>
      <webElementGuid>35919554-5161-4641-b7ec-a9d270231b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:op()')]</value>
      <webElementGuid>6f2f25ba-1258-4c00-9f85-d6ad16a3be59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[3]/a</value>
      <webElementGuid>e68afeda-a4d4-4fd0-b972-fa8a875b59a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:op()' and @id = 'itemTextLink1' and (text() = 'BIBLIOGRAPHY' or . = 'BIBLIOGRAPHY')]</value>
      <webElementGuid>5d20ec51-f0ac-4390-bea2-22e5334929b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
