<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DTR199219</name>
   <tag></tag>
   <elementGuidId>254bd74e-7267-45f3-ae41-e71a21bca5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.referencia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultsTable']/tbody/tr[3]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5cf616b7-a311-409a-b264-ce74ffaec5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>referencia</value>
      <webElementGuid>c89ee4bb-8fb8-4198-a501-0e438bac496a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:viewReferenceDetail(63186298,'../..');</value>
      <webElementGuid>9e8362c4-7f2a-4de3-82de-8c3f96d42606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								DTR\1992\19
							</value>
      <webElementGuid>6f37b784-8b44-4bf9-a12f-805b4983fdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsTable&quot;)/tbody[1]/tr[3]/td[@class=&quot;tdContent&quot;]/a[@class=&quot;referencia&quot;]</value>
      <webElementGuid>7c171772-f4bb-4e5e-af0f-072c92f1924e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultsTable']/tbody/tr[3]/td[2]/a</value>
      <webElementGuid>c5f9426d-1aad-4fd1-87b7-b4e4a527e3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DTR\1992\19')]</value>
      <webElementGuid>da4c5f2c-3de5-4b54-95e4-5b1491368e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::a[1]</value>
      <webElementGuid>5f3e59d5-5126-4526-8476-96b9a7dd4b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bibliography type'])[1]/following::a[1]</value>
      <webElementGuid>e1f5d8cb-1be2-4157-9189-1b512755c79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='artículo'])[1]/preceding::a[1]</value>
      <webElementGuid>e9b335fc-ef3a-4f9d-b81a-b878ebf9b0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DTR\1992\19']/parent::*</value>
      <webElementGuid>1c7199cd-431a-46f7-9b0a-21cedab63a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:viewReferenceDetail(63186298,'../..');&quot;)]</value>
      <webElementGuid>1c174395-e654-4b67-a246-fb1bea11a5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/a</value>
      <webElementGuid>46fd2255-f593-4c30-85a7-dc0ddefc5a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:viewReferenceDetail(63186298,&quot; , &quot;'&quot; , &quot;../..&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = '
								DTR\1992\19
							' or . = '
								DTR\1992\19
							')]</value>
      <webElementGuid>e7d33206-62b9-4dcf-aeff-54c00ca9517e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
