<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logoff</name>
   <tag></tag>
   <elementGuidId>3938e3c9-9b49-4575-9039-5db2dfe9f533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lnkHeaderLogOut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkHeaderLogOut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a85eb6b-9cca-4c07-9ef4-061e5d24ff5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkHeaderLogOut</value>
      <webElementGuid>5d96f7aa-b2f5-45e9-8968-8928cdcfb0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/GCMSWeb/sso/logoff.do</value>
      <webElementGuid>a4279711-efd4-41f5-a24f-65c246a636ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>eraseCookie('clickedFolder');eraseCookie('highlightedTreeviewLink');</value>
      <webElementGuid>6781d60b-22f8-4b88-8a3c-4a6ba5c8d096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logoff</value>
      <webElementGuid>95bcfc17-447d-4762-a0ca-9a572153ce71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkHeaderLogOut&quot;)</value>
      <webElementGuid>0235b9fe-88c9-496f-8e7e-47a1545127dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnkHeaderLogOut']</value>
      <webElementGuid>460684d1-fca7-4cca-b215-be3aa4dfa8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logoff')]</value>
      <webElementGuid>d4cc2c37-0d4d-41ab-979a-e373be85dec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/following::a[1]</value>
      <webElementGuid>135b81d2-41c6-44e7-b11d-1b0ddc85abf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product workbench'])[1]/following::a[2]</value>
      <webElementGuid>dc79d3cb-4970-478b-9c71-e92ebd418bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Options'])[1]/preceding::a[1]</value>
      <webElementGuid>b05ebc61-ce93-4688-af0b-7e335d8d5dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BIBLIOGRAPHY'])[1]/preceding::a[3]</value>
      <webElementGuid>9c69dcf2-9ce2-4fd6-9393-bca823ee7dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logoff']/parent::*</value>
      <webElementGuid>89c641bd-4464-4327-8f6e-11ee16b3025b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/GCMSWeb/sso/logoff.do')]</value>
      <webElementGuid>82cdc844-f0f9-4218-8cbb-79498c16f948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[5]/a</value>
      <webElementGuid>e2b2b556-89aa-42da-a062-f5ca2056aff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkHeaderLogOut' and @href = '/GCMSWeb/sso/logoff.do' and (text() = 'Logoff' or . = 'Logoff')]</value>
      <webElementGuid>d1e2349b-e2d2-4fda-851c-c55b842e082a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
