<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BIBLIOGRAPHY</name>
   <tag></tag>
   <elementGuidId>dea6ab2b-4d50-48f8-ac3e-60c5382495e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb6ed024-3e3e-44f6-aa31-11ec1108752a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>84b66fd1-45d7-4428-afcb-78f580707047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:op()</value>
      <webElementGuid>73e53042-be33-4690-b3a1-0b4992efe8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>44f59f66-9e40-46ee-90fc-0f578293ccf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink1</value>
      <webElementGuid>2771867d-31a5-435b-bb54-aa4899ee5fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clickOnFolder(&quot;1&quot;)</value>
      <webElementGuid>3ac2907e-3e18-4ce5-8081-d8f5b5ebf684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BIBLIOGRAPHY</value>
      <webElementGuid>9ce4c9b2-01f6-423d-b208-453cca6efc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink1&quot;)</value>
      <webElementGuid>12573a8c-5d73-4c5c-be56-dd3c2a65bbf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink1']</value>
      <webElementGuid>f70c8115-3631-464e-9d2e-73ecde135c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder1']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>c16dba14-7566-486b-bc93-3db3f5c1b683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BIBLIOGRAPHY')]</value>
      <webElementGuid>6df032de-c022-4ee9-b69a-6838b62fc69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Options'])[1]/following::a[3]</value>
      <webElementGuid>e7a0d3cf-bf7a-457f-952e-ad58c53b5122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logoff'])[1]/following::a[3]</value>
      <webElementGuid>b4bafef2-47f7-4607-b8ee-6d7c4bd7540b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JURISPRUDENCE'])[1]/preceding::a[2]</value>
      <webElementGuid>c549883d-bf38-4028-8503-b7be6b8fc764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRACTICAL CONTENT'])[1]/preceding::a[4]</value>
      <webElementGuid>dc0c1849-65d1-46cb-b425-86a1c68f7cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BIBLIOGRAPHY']/parent::*</value>
      <webElementGuid>a54c29a4-9905-4e1c-83e7-01638683c181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:op()')]</value>
      <webElementGuid>c66b3902-bd32-4abc-8b42-a286dc43835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[3]/a</value>
      <webElementGuid>91a7a4dd-e3e8-45f5-8aac-f77f71b05177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:op()' and @id = 'itemTextLink1' and (text() = 'BIBLIOGRAPHY' or . = 'BIBLIOGRAPHY')]</value>
      <webElementGuid>2c54a2d6-fd9a-402c-a5dd-31ec3abf953a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
