<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>9730b15b-b778-482b-81bb-ebf33ee2ffb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b71c2a9-7da8-4adb-af76-1d591364659c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>984323a1-132d-474d-82e2-4cdd92e39fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../biblio/doMenu.do?dispatch=cons</value>
      <webElementGuid>18f32143-f840-4007-9910-302da7e4904b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>a641783b-8302-4a33-b28d-cbf436921b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink3</value>
      <webElementGuid>a837f396-79b3-42cc-be59-f03f365b5f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clickOnFolder(&quot;3&quot;)</value>
      <webElementGuid>de40990a-67f6-483a-9482-585ba0f50d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>249b1281-75bf-4b4a-bc5a-76cde0707ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink3&quot;)</value>
      <webElementGuid>0058731b-5548-4596-82af-1593512b23f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink3']</value>
      <webElementGuid>aaeac06f-f5ca-4591-a080-fe88e7d7b791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder3']/table/tbody/tr/td[5]/a</value>
      <webElementGuid>63223115-c06a-4330-89fa-ea6bf5a5741c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Search')]</value>
      <webElementGuid>17e8af97-59e5-45da-a6ec-6a35bd201d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bibliographic documents'])[1]/following::a[2]</value>
      <webElementGuid>e81535a2-d6ce-45b3-9076-c5b73fea00a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BIBLIOGRAPHY'])[1]/following::a[4]</value>
      <webElementGuid>268507e2-6795-49c9-aa15-541e01a3e6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result list'])[1]/preceding::a[2]</value>
      <webElementGuid>2e748aee-bd19-426d-a73a-3dcb817a6792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Inbox'])[1]/preceding::a[4]</value>
      <webElementGuid>b9074a69-7f5f-439e-a005-2e48dfd5ad1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>e793688f-674a-4f77-8395-409964df32e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../biblio/doMenu.do?dispatch=cons')]</value>
      <webElementGuid>595223d6-caca-447e-b5a0-c7356c40f5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[5]/a</value>
      <webElementGuid>66012497-429b-434d-8aec-c06975e9c3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../biblio/doMenu.do?dispatch=cons' and @id = 'itemTextLink3' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>a9d1a063-ddbb-445c-af51-d0d3d79e0415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
