<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Language_buttonInform</name>
   <tag></tag>
   <elementGuidId>9524a7bc-a9d0-4582-9427-9af22c6f1792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.buttonInform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Logon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dabc4723-a098-484f-b196-778d9ebd5d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b7cc79bc-5196-45be-8ba1-c08029d54058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonInform</value>
      <webElementGuid>3fdb3b71-c5dd-4055-8643-4d2e8609b8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Logon</value>
      <webElementGuid>d8386d4f-450b-4ae7-887f-5c7f4bb34fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:normalizarUserID();</value>
      <webElementGuid>a49c7a39-56d0-46a2-bb79-662065ecdd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[3]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[@class=&quot;buttonInform&quot;]</value>
      <webElementGuid>96b09d60-7d5f-4b53-8ce3-68dd3882f371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Logon']</value>
      <webElementGuid>098cc636-6319-4c02-a255-a127ae7f52d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>92a60311-f006-484e-adae-016e8c55529c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>a080c92f-1568-4e7f-bc6c-77fac8765a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
