<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Language_buttonInform</name>
   <tag></tag>
   <elementGuidId>19ed0260-5c8e-45ff-bb8e-dde2d2a65c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.buttonInform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Logon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8be28f7-678f-4320-8651-b0d6c0aa4ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bf0fb031-2c44-4ca8-a595-08683d1dc78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonInform</value>
      <webElementGuid>400266a5-56c4-4e7a-8b1f-525c8f96f038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Logon</value>
      <webElementGuid>7fbc8cf9-b4a0-41ae-8c66-6f09769c76e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:normalizarUserID();</value>
      <webElementGuid>a798009d-7cb8-4a7e-9053-0399f18236aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[3]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[@class=&quot;buttonInform&quot;]</value>
      <webElementGuid>3074ca1f-b2f0-4ff7-b4ba-d9cd9c1031a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Logon']</value>
      <webElementGuid>54f790d5-3ae0-4cee-bde8-3680ad4b2a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>c258e753-4342-4e7a-a9a2-278e30834898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>1e147c32-ec2f-4f45-91e0-562333d94e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
